name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
# on:
#   schedule:
#   - cron: "0 2 * * 1-5"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker Image
      run: docker build . --file Dockerfile --tag eureka
    - name: Run th Docker Image
      run: docker run -p 8080:8080 eureka && curl localhost:8080
